### ISSUE TITLE
Faltan los contribuidores del Proyecto

### ISSUE THREAD

**Issue by TeenBiscuits** [TeenBiscuits/Pro2324#50]
@all-contributors
please add @TeenBiscuits  for code, content, doc. 
please add @Fraagaa  for code.
please add @sneiira for code.
please add @dza205 for code.
please add @danielfeitopin for content.

**Comment by dza205** [comment]
Ping a la una 💀

**Comment by TeenBiscuits** [comment]
Contestaste tu antes que el bot xd

**Comment by TeenBiscuits** [comment]
@all-contributors
please add @TeenBiscuits for code, content, doc.
please add @Fraagaa for code.
please add @sneiira for code.
please add @dza205 for code.
please add @danielfeitopin for content.

**Comment by TeenBiscuits** [comment]
@all-contributors
please add @sneiira for code.
please add @dza205 for code.
please add @danielfeitopin for content.

**Comment by TeenBiscuits** [comment]
Ultimo ping lo juro

**Comment by TeenBiscuits** [comment]
@all-contributors
please add @sneiira for code.
please add @dza205 for code.
please add @danielfeitopin for content.

**Comment by TeenBiscuits** [comment]
@all-contributors
please add @TeenBiscuits for code, content, doc.

**Comment by TeenBiscuits** [comment]
@all-contributors
please add @TeenBiscuits for code, content, doc.

**Comment by TeenBiscuits** [comment]
@all-contributors please add @TeenBiscuits for code, content, doc.

**Comment by TeenBiscuits** [comment]
@all-contributors please add @TeenBiscuits for code, content, doc.

**Comment by TeenBiscuits** [comment]
@all-contributors please add @TeenBiscuits for code, content, doc.

**Comment by TeenBiscuits** [comment]
@all-contributors
please add @Fraagaa  for code.

**Comment by TeenBiscuits** [comment]
@all-contributors
please add @sneiira for code.

**Comment by TeenBiscuits** [comment]
@all-contributors
please add @dza205 for code.

**Comment by TeenBiscuits** [comment]
@all-contributors
please add @danielfeitopin for content.

**Comment by TeenBiscuits** [comment]
Y ya estaría, lo siento mucho a quienes os hice ping, ya que estáis por el repositorio echadle un ojo a la página web [ENLACE](https://teenbiscuits.github.io/Pro2324/pro2324.html) y a come he resctructurado y cambiado el repo.
