### ISSUE TITLE
📖 Normas de contribución al repositorio de PRO2

### ISSUE THREAD

**Issue by dza205** [TeenBiscuits/Pro2324#72]
Ya que el plagio no está permitido en ninguna circunstancia y se castiga a las dos partes por igual creo que deberíamos incluir algo al respecto en las reglas de contribución para PRO2 o bloquear la contribución de código directamente @TeenBiscuits

**Comment by TeenBiscuits** [comment]
Estaba en ello justo

**Comment by TeenBiscuits** [comment]
Voy a aprovechar y cambio para adaptarlo a lo de los proyectos
